on:
  push:
    branches:
      - develop
      - staging
      - main
  pull_request:
    branches:
      - develop
  workflow_dispatch:
    branches:
      - main
      - develop
      - staging
      - feature/**
      
jobs:
  build:
    uses: devfrensh/cicd-templates/.github/workflows/npm.yml@main
    secrets: inherit
  sonar:
    uses: devfrensh/cicd-templates/.github/workflows/sonar.yml@main
    needs: build
    secrets: inherit
  registry:
    uses: devfrensh/cicd-templates/.github/workflows/registryHarborV2.yml@main
    needs: sonar
    secrets: inherit
  promote:
    if: ${{ success() && github.ref_name == 'develop' }}
    uses: devfrensh/cicd-templates/.github/workflows/promoteHarbor.yml@main
    needs: registry
    secrets: inherit