on:
  push:
    branches:
      - develop
      - staging
      - main
  pull_request:
    branches:
      - develop
  workflow_dispatch:
    branches:
      - main
      - develop
      - staging
      - feature/**
  
jobs:
  build:
    uses: devfrensh/cicd-templates/.github/workflows/npm.yml@main
    secrets: inherit
  sonar:
    uses: devfrensh/cicd-templates/.github/workflows/sonar.yml@main
    secrets: inherit
    needs: build
  registry:
    uses: devfrensh/cicd-templates/.github/workflows/registryHarborV2.yml@main
    secrets: inherit
    needs: sonar
    environment: ${{ github.ref_name }}   # activa develop / staging / main