on:
  push:
    branches:
      - develop
      - staging
      - main
  pull_request:
    branches:
      - develop
  workflow_dispatch:
    branches:
      - main
      - develop
      - staging
      - feature/**
jobs:
  build:
    name: Build & Dependencies
    uses: devfrensh/cicd-templates/.github/workflows/npm.yml@main
    secrets: inherit
  sonar:
    name: Code Analysis (SonarQube)
    uses: devfrensh/cicd-templates/.github/workflows/sonar.yml@main
    secrets: inherit
    needs: build
  registry:
    name: Build & Push Image (Harbor)
    uses: devfrensh/cicd-templates/.github/workflows/registryHarborV2.yml@main
    secrets: inherit
    needs: sonar
  promote:
    name: Promote Image (Crane)
    needs: registry
    if: ${{ success() && github.ref_name == 'develop' }}
    uses: devfrensh/cicd-templates/.github/workflows/promoteHarbor.yml@main
    secrets: inherit